# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-03 09:40
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
