# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 10:08
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20181003_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
